export const GET_BOOKS_PENDING = "GET_BOOKS_PENDING";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILED = "GET_BOOKS_FAILED";

export const ADD_BOOK_PENDING = "ADD_BOOK_PENDING";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILED = "ADD_BOOK_FAILED";

export const REMOVE_BOOK_PENDING = "REMOVE_BOOK_PENDING";
export const REMOVE_BOOK_SUCCESS = "REMOVE_BOOK_SUCCESS";
export const REMOVE_BOOK_FAILED = "REMOVE_BOOK_FAILED";
